# Commented sections below can be used to run tests on the CI server
# https://simulatedgreg.gitbooks.io/electron-vue/content/en/testing.html#on-the-subject-of-ci-testing
version: 0.1.{build}

deploy:
  - provider: Environment
    name: production
    on:
      branch: redesign
  - provider: Environment
    name: production
    on:
      appveyor_repo_tag: true
# branches:
#   only:
#     - redesign

image: Visual Studio 2017
platform:
  - x64

cache:
  # - node_modules
  # - '%APPDATA%\npm-cache'
  # - '%USERPROFILE%\.electron'
  # - '%USERPROFILE%\AppData\Local\Yarn\cache'

init:
  - git config --global core.autocrlf input

install:
  - ps: Install-Product node 8 x64
  # - choco install yarn --ignore-dependencies
  - git reset --hard HEAD
  - yarn
  - node --version

build_script:
  #- yarn test
  - yarn build

test: off
